version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: rectangles
      POSTGRES_PASSWORD: rectangles
      POSTGRES_DB: rectangles
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: >
      sh -c "python db_prerequisites.py && pytest test_api.py && flask run --host=0.0.0.0"
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      DATABASE_URL: postgresql://rectangles:rectangles@db:5432/rectangles
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  postgres_data:
